/**
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  configSyncSidebar: [
    {
      type: "category",
      collapsed: false,
      label: "🚀 Getting Started",
      items: [
        "getting-started/installation",
        "getting-started/motivation",
        "getting-started/cli",
        "getting-started/admin-gui",
        "getting-started/config-types",
        "getting-started/workflow",
        "getting-started/naming-convention",
        // "dev-docs/usage-information",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "⚙️ Configuration",
      items: [
        "configuration/introduction",
        "configuration/sync-dir",
        "configuration/minify",
        "configuration/import-on-bootstrap",
        "configuration/custom-types",
        "configuration/soft",
        "configuration/excluded-types",
        "configuration/excluded-config",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "📦 API",
      items: [
        "api/plugin-config-types",
      ],
    },
    {
      type: "category",
      collapsed: false,
      label: "♻️ Upgrading",
      items: [
        "upgrading/generic-update",
      ],
    },
  ],
};

module.exports = sidebars;
