#!/bin/bash

Color_Off='\033[0m'
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue

LOCAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
REGEX="^(main|master|develop)|(hotfix|release|feature|test|fix|chore|docs|refactor)\/[a-z0-9._-]+$"
ERROR_MSG="Branch name must match regex \"${REGEX}\""

if [[ ! $LOCAL_BRANCH =~ $REGEX ]]; then
  printf "${BRed}Bad branch name ${BBlue}\"$LOCAL_BRANCH\"\n"
  printf "${BYellow}$ERROR_MSG\n"
  printf "The git-flow branch patten is expected, for details see https://gist.github.com/boazpoolman/42629d941b5f747734d296e02ecf737d\n"
  printf "pre-commit hook failed (add --no-verify to bypass)\n"
  exit 1
fi

exit 0
